language: objective-c
osx_image: xcode8.3

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - cd OneDriveSDK && pod install

script : 
    - xcodebuild -workspace OneDriveSDK.xcworkspace -scheme OneDriveSDKTests -sdk iphonesimulator build-for-testing
    - xctool -workspace OneDriveSDK.xcworkspace -scheme OneDriveSDKTests -sdk iphonesimulator run-tests

