language: objective-c

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - cd OneDriveSDK && pod install

xcode_workspace: OneDriveSDK\OneDriveSDK.xcworkspace
xcode_scheme: OneDriveSDKTests