# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OneDriveSDK' do
    pod 'ADALiOS', '~> 1.0.2'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

