# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OneDriveSDK' do
    pod 'ADAL', '~> 1.2'
    pod 'Base32', '~> 1.1'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

